name: Amethyst CI via GitHub Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:

  testandclippy:
    name: Code Checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        toolchain: [stable, nightly]
        include:
        - os: macos-latest
          FEATURES: metal
        - os: windows-latest
          FEATURES: vulkan
        - os: ubuntu-latest
          FEATURES: vulkan

    steps:
      - uses: actions/checkout@v2

      - name: install linux deps
        run: |
          sudo apt update
          sudo apt install gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev
        if: contains(matrix.os, 'ubuntu')

      - name: install ${{ matrix.toolchain }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          components: rustfmt, clippy
          override: true

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

#      - name: install clippy
#        run: rustup component add clippy
#        if: contains(matrix.toolchain, 'stable')

      - name: cargo clippy amethyst
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features=${{matrix.FEATURES}}
        if: contains(matrix.toolchain, 'stable')

      - name: cargo test amethyst
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=${{matrix.FEATURES}}
